hospitalization/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('plan.urls'))
]

plan/urls.py
from django.urls import path
from . import views


app_name = 'plan'
urlpatterns = [
    path('', views.AuthView.as_view(), name='login'),
    path('logout/', views.ExitView.as_view(), name='logout'),
    path('main/', views.MainView.as_view(), name='main'),
    path('new/', views.NewPatientView.as_view(), name='new'),
    path('<int:pk>/', views.UpdatePatientView.as_view(), name='update'),
    path('table/', views.csv_response, name='table'),
    path('week/', views.week_list, name='week'),
    path(views.directory+'<path:filename>/', views.download),
    #path('test/', views.test, name='test'),
]

plan/models.py
from pathlib import Path
from django.db import models
from django.db.models.functions import datetime


# Create your models here.
class Files(models.Model):
    docs_directory = 'plan/src/'
    doc = models.FileField(upload_to=docs_directory)
    add_date = models.DateTimeField(auto_now_add=True)
    """
    # Awaiting the PACS interface information.
    dicom_directory = 'plan/dicom/'
    pid = models.PositiveBigIntegerField() # ManyToManyField ???
    dicom = models.FileField(upload_to=dicom_directory)
    keys = models.CharField(max_length=16)
    """
    def delete(self):
        """Remove a file when the entry is deleted."""
        super().delete()
        Path(self.doc.name).unlink()
    
    def __str__(self):
        return Path(self.doc.name).name

class Patients(models.Model):
    foreign_key = models.ForeignKey(Files, on_delete=models.CASCADE, null=True)
    plain_text = models.TextField(blank=True)
    confirmation = models.BooleanField('Статус проверки', default=False)
    physician = models.CharField('Врач', max_length=200)
    name = models.CharField('Пациент', max_length=200)
    medical_card = models.CharField('Номер карты', max_length=7, blank=True)
    phone = models.CharField('Телефон', max_length=18, blank=True)
    hosp_date = models.DateField('Госпитализация', null=True, blank=True)
    oper_date = models.DateField('Операция', null=True, blank=True)
    diagnosis = models.TextField('Диагноз', blank=True)
    icd10 = models.CharField('МКБ', max_length=6, blank=True)
    htmc_code = models.CharField('Код ВМП', max_length=50, blank=True)
    quota = models.TextField('Квота', blank=True)
    equipment_types = models.TextChoices('Типы', 'Стандарт Нейромонитор AWAKE')
    equipment = models.CharField(
        'Тип', 
        max_length=15,
        choices=equipment_types.choices, 
        default='Стандарт'
    )
    notes = models.TextField('Заметки', blank=True)
    alteration_user = models.CharField(max_length=16, default='Unauthorized')
    alteration_date = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name.partition(' ')[0]

plan/forms.py
from datetime import date, timedelta
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from django.core.validators import FileExtensionValidator, MinValueValidator
from django.utils.translation import gettext_lazy as _
from .models import Patients, Files


# Create your forms here.
class AuthForm(AuthenticationForm):
    username = UsernameField(
        label=_('Логин'), 
        widget=forms.TextInput(attrs={"autofocus": True})
    )
    password = forms.CharField(
        label=_('Пароль'),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "current-password"}),
    )
    error_messages = {
        "invalid_login": _(
            "Пожалуйста, введите корректное имя пользователя и пароль. "
            "Проверьте регистр вводимых данных."
        ),
        "inactive": _("Этот аккаунт не активен."),
    }

class NewPatientForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        md = self.min_date()
        m = _('Дата должна быть равна или позднее %(limit_value)s.')
        self.fields['hosp_date'].validators=[MinValueValidator(md, m)]
        self.fields['oper_date'].validators=[MinValueValidator(md, m)]
        self.fields['alteration_user'].required=False
        self.fields['equipment'].required=False
        for field in self.fields.values():
            field.error_messages = {
                'required': 'Поле {f} необходимо заполнить.'.format(f=field.label)
            }
    
    def min_date(self):
        """Return the minimum date value for the validator."""
        target_day = date.today() - timedelta(days=7)
        while target_day.isoweekday() != 1:
            target_day -= timedelta(days=1)
        return target_day
    
    foreign_key = forms.ModelChoiceField(
        required=False,
        queryset=Files.objects.all(),
        widget=(forms.HiddenInput())
    )
    timestamp = forms.DateTimeField(
        required=False,
        widget=(forms.HiddenInput())
    )
    class Meta:
        model = Patients
        exclude = [
            'alteration_date'
        ]
        widgets = {
            'plain_text': forms.HiddenInput(),
            'alteration_user': forms.HiddenInput(),
            'hosp_date': forms.DateInput(attrs={'type': 'date'}),
            'oper_date': forms.DateInput(attrs={'type': 'date'}),
        }

class UploadFileForm(forms.Form):
    file = forms.FileField(
        label='Консультативное заключение',
        validators=[FileExtensionValidator(
            allowed_extensions=['rtf', 'docx'],
            message = _(
                "Файл типа “%(extension)s” не поддерживается. "
                "Доступные типы файлов: %(allowed_extensions)s."
            )
        )]
    )

class MultiUploadFileForm(forms.Form):
    file = forms.FileField(
        widget=forms.ClearableFileInput(attrs={'multiple': True})
    )

plan/views.py
import asyncio
import logging
import re
from datetime import date, datetime, timedelta
from csv import writer
from pathlib import Path
from shutil import make_archive, rmtree 
from xml.etree.cElementTree import XML
from zipfile import ZipFile
from zoneinfo import ZoneInfo
from striprtf.striprtf import rtf_to_text
from django.db.models import F, Q
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.http import (
    FileResponse,
    HttpResponse, 
    HttpResponseRedirect, 
    HttpResponseForbidden
)
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView, CreateView, UpdateView
from django.views.generic.edit import DeletionMixin
from django.urls import reverse
from .forms import (
    AuthForm,
    NewPatientForm,
    UploadFileForm,
    MultiUploadFileForm
)
from .models import Files, Patients


# Create your views here.
logger = logging.getLogger('django.server.file') # 'django.server.file'
directory = Files.docs_directory

@login_required
def download(request, filename: str) -> FileResponse: 
    """Return a file to the client side."""
    return FileResponse(open(directory+filename, 'rb'))

async def slice_load(request, filename: str, semaphore: int) -> FileResponse: 
    """Return a DICOM slice.
    
    *Template. Not for use.
    """
    async with semaphore:
        await asyncio.sleep(0.5) # RadiAnt issues (DON'T CHANGE!)
        return FileResponse(
            open('plan/dicom/'+filename, 'rb'), as_attachment=True
        )

async def dicom(
    request, ae_title: str, patient_id: int
) -> FileResponse | HttpResponseForbidden:
    """Return DICOM slices to the viewer.
    
    *Template. Not for use. Tested with Orthanc only. Awaiting the
    PACS interface information.
    """
    if Files.objects.filter(keys=ae_title).exists():
        data = Files.objects.filter(pid=patient_id)
        slices = [f for f in data]
        semaphore = asyncio.Semaphore(5)
        tasks = [slice_load(None, s, semaphore) for s in slices]
        await asyncio.gather(*tasks)
    else:
        return HttpResponseForbidden()

class AuthView(LoginView):
    authentication_form = AuthForm
    template_name = 'plan/login.html'
    next_page = '/main/'
    
    def get_context_data(self, **kwargs) -> dict: 
        if settings.DEBUG:
            kwargs['debug'] = 'ВКЛЮЧЁН РЕЖИМ ОТЛАДКИ!!!'
        if 'Mozilla/4.0' in self.request.headers['User-Agent']:
            kwargs['old_browser'] = True
        return super().get_context_data(**kwargs)
    
    def form_valid(self, form) -> HttpResponse:
        self.request.session.set_expiry(3600)
        return super().form_valid(form)

class ExitView(LoginRequiredMixin, LogoutView):
    template_name = 'plan/logout.html'
    next_page = '/'

class MainView(LoginRequiredMixin, ListView):
    template_name = 'plan/main.html'
    queryset = Patients.objects.order_by(F('hosp_date').asc(nulls_first=True))
    
    def get_context_data(self, **kwargs) -> dict:
        kwargs['calendar'] = self.calendar_data()
        if 'Mozilla/4.0' in self.request.headers['User-Agent']:
            kwargs['old_browser'] = True
        return super().get_context_data(**kwargs)
    
    def calendar_data(self) -> list:
        """Return five weeks calendar data for the main.html template."""
        now = datetime.now()
        target_day = now - timedelta(days=7)
        while target_day.isoweekday() != 1:
            target_day -= timedelta(days=1)
        months = [
            'Января', 
            'Февраля', 
            'Марта', 
            'Апреля', 
            'Мая', 
            'Июня', 
            'Июля', 
            'Августа', 
            'Сентября', 
            'Октября', 
            'Ноября', 
            'Декабря'
        ]
        weekdays = [
            'Понедельник', 
            'Вторник', 
            'Среда', 
            'Четверг', 
            'Пятница', 
            'Суббота', 
            'Воскресенье'
        ]
        five_weeks = []
        one_week = []
        for i in range(35):
            day = target_day.date().day
            month = months[target_day.date().month-1]
            year = target_day.date().year
            weekday = weekdays[target_day.date().weekday()]
            past = 'id_past'
            if target_day == now:
                past = 'id_today'
            elif target_day > now:
                past = 'id_future'
            day_dict = {
                'date': f'{day} {month} {year}',
                'weekday': weekday,
                'past': past,
                'hosp': self.queryset.filter(hosp_date=target_day.date()),
                'oper': self.queryset.filter(oper_date=target_day.date())
            }
            one_week.append(day_dict)
            if (i+1)%7 == 0:
                five_weeks.append(one_week)
                one_week = []
            target_day += timedelta(days=1)
        return five_weeks

@login_required
def csv_response(request) -> HttpResponse:
    """Returns all database data as a csv table."""
    response = HttpResponse(headers={
        'Content-Type': 'text/csv; charset=cp1251',
        'Content-Disposition': 'attachment; filename="plan.csv"',
    })
    to_csv = writer(response)
    to_csv.writerow([
        'Дата госпитализации', 'Дата операции', 'Врач', 'Пациент', 
        'Номер карты', 'Телефон', 'Диагноз', 'МКБ', 'Код ВМП', 
        'Тип', 'Заметки'
    ])
    patients = Patients.objects.all().values_list(
        'hosp_date', 'oper_date', 'physician', 'name', 
        'medical_card', 'phone', 'diagnosis', 'icd10', 'htmc_code', 
        'equipment', 'notes'
    )
    for patient in patients:
        to_csv.writerow(patient)
    return response

@login_required
def week_list(request) -> FileResponse | HttpResponse:
    """Return a list of scheduled surgeries for the next week."""
    try:
        files = Path.cwd()/'plan'/'src'/'files'
        old = files/'week.docx'
        old.unlink(missing_ok=True)
        template = files/'template.docx'
        copy = files/'copy.docx'
        copy.write_bytes(template.read_bytes())
        temp = files/'temp'
        rmtree(temp, ignore_errors=True)
        temp.mkdir()
        with ZipFile(copy, 'r') as z:
            z.extractall(temp)
        copy.unlink()
        with open(temp/'word'/'document.xml', 'r', encoding='utf8') as f:
            new = f.read()
            next_monday = date.today()
            # matching with the current monday is correctly
            while next_monday.isoweekday() != 1:
                next_monday += timedelta(days=1)
            next_sunday = next_monday + timedelta(days=6)
            n_m = next_monday.strftime('%d.%m.%Y')
            n_s = next_sunday.strftime('%d.%m.%Y')
            new = new.replace(
                '<w:t>дата</w:t>', 
                f'<w:t>Неделя с {n_m} по {n_s}</w:t>'
            )
            queryset = Patients.objects.filter(
                oper_date__range=(next_monday, next_sunday)
            ).values_list(
                'name', 'medical_card', 'diagnosis', 'quota', 'htmc_code'
            )
            mod_queryset = []
            for query in queryset:
                mod_queryset.append(list(query))
                i = mod_queryset[-1]
                i[0] = i[0] + ', №' + i[1]
                i[3] = i[3] + ' ' + i[4]
                i.pop(1)
                i.pop()
            for query in mod_queryset:
                for i in query:
                    new = new.replace('<w:t>т</w:t>', f'<w:t>{i}</w:t>', 1)
            new = new.replace('<w:t>т</w:t>', '<w:t></w:t>')
        with open(temp/'word'/'document.xml', 'w', encoding='utf8') as f:
            f.write(new)
        make_archive(copy, 'zip', temp)
        rmtree(temp, ignore_errors=True)
        week = files/'copy.docx.zip'
        week.rename(Path(week.parent, 'week.docx'))
        return FileResponse(
            open(files/'week.docx', 'rb'), as_attachment=True
        )
    except Exception as err:
        logger.error(err, exc_info=True)
        return HttpResponse('Произошла ошибка. Данные записаны в лог-файл.')

class NewPatientView(LoginRequiredMixin, CreateView):
    form_class = NewPatientForm
    template_name = 'plan/new.html'
    success_url = '/main/'
    
    def __init__(self, **kwargs) -> None:
        super().__init__(**kwargs)
        self.remove_files()
        self.remove_entries()
    
    def get_initial(self) -> dict:
        self.initial['alteration_user'] = self.request.user.username
        return super().get_initial()
    
    def get_context_data(self, upload_form=UploadFileForm(), **kwargs) -> dict:
        kwargs['upload_form'] = upload_form
        if 'Mozilla/4.0' in self.request.headers['User-Agent']:
            kwargs['old_browser'] = True
        return super().get_context_data(**kwargs)
    
    def post(self, request, *args, **kwargs) -> HttpResponse:
        if 'pat_obj' in request.POST:
            self.object = None
            return super().post(request, *args, **kwargs)
        elif 'file_obj' in request.POST:
            form = UploadFileForm(request.POST, request.FILES)
            if form.is_valid():
                file_instance = Files(doc=form.cleaned_data['file'])
                file_instance.save()
                inits = {'alteration_user': self.request.user.username}
                try:
                    if file_instance.doc.path.endswith('.rtf'):
                        plain_text = self.read_rtf(file_instance)
                    elif file_instance.doc.path.endswith('.docx'):

plan/templates/plan/head.html
{% load static %}
{% if old_browser %}
    <a href="{% url 'plan:main' %}">Главная</a>
    <a href="{% url 'plan:new' %}">Новый пациент</a>
    <a href="{% static 'files/htmc.pdf' %}">Коды ВМП</a>
    <a href="{% url 'plan:table' %}">Госпитализация</a>
    <a href="{% url 'plan:week' %}">Операции</a>
    <a href="{% url 'plan:logout' %}">Выход</a>
{% else %}
    <div id="head_menu">
        <img src="{% static 'images/red-cross.png' %}" alt="Госпитализация">
        <ul>
            <li><a href="{% url 'plan:main' %}">Главная</a></li>
            <li><a href="{% url 'plan:new' %}">Новый пациент</a></li>
            <li><a href="{% static 'files/htmc.pdf' %}">Коды ВМП</a></li>
            <li><a href="{% url 'plan:table' %}">Госпитализация</a></li>
            <li><a href="{% url 'plan:week' %}">Операции</a></li>
        </ul>
        
    </div>
    <div class="dropdown_menu">
        <button class="drop_menu_button">Меню</button>
        <br>
        <div class="dropdown_menu_content">
            <a href="{% url 'plan:main' %}">Главная</a>
            <a href="{% url 'plan:new' %}">Новый пациент</a>
            <a href="{% static 'htmc.pdf' %}">Коды ВМП</a>
            <a href="{% url 'plan:table' %}">Госпитализация</a>
            <a href="{% url 'plan:week' %}">Операции</a>
        </div>
    </div>
    <div class="dropdown_reference">
        <button class="drop_reference_button" title="Справка">
            <img src="{% static 'images/doubts.png' %}">
        </button>
        <div class="dropdown_reference_content">
            <p id="calendar">
                При внесении новой записи с использованием консультативных
                заключений, созданных на основе приложенных шаблонов в
                форматах .rtf и .docx, система попытается выполнить
                автозаполнение полей информацией из загруженного документа.
                Символ меню правого края экрана вызывает общий список
                пациентов.<br>
                <a id="id_red" href="">Фамилия</a> - пациент не внесён в очередь госпитализации.<br>
                <a id="id_green" href="">Фамилия</a> - данные пациента получены отделом госпитализации.<br>
                <a id="id_based" href="">Фамилия</a> - стандартное операционное оборудование.<br>
                <a id="id_neuro" href="">Фамилия</a> - операция с нейрофизиологическим мониторингом.<br>
                <a id="id_awake" href="">Фамилия</a> - интраоперационное пробуждение пациента (AWAKE).<br>
            </p>
        </div>
    </div>
    <div id="logout_button">
        <a href="{% url 'plan:logout' %}" title="Выход">
            <img src="{% static 'images/logout.png' %}">
        </a>
    </div>
{% endif %}

plan/templates/plan/login.html
<!DOCTYPE html>
<html>
    {% load static %}
<head>
    <title>Госпитализация</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="icon" type="image/png" href="{% static 'favicon.png' %}">
    <meta charset="utf-8">
    <meta name="description" content="Планирование госпитализации">
    <!--[if IE]><script src="{% static 'html5shiv/html5shiv.js' %}"></script><![endif]-->
    <!--[if IE]><script src="{% static 'html5shiv/html5shiv-printshiv.js' %}"></script><![endif]-->
</head>
<body>
    {% if old_browser %}
        {% if debug %}
            <h1>{{ debug }}</h1><br>
        {% endif %}
        <h1>ПЛАН ГОСПИТАЛИЗАЦИИ</h1><br>
        {% if user.is_authenticated %}
            <strong>
                <a href="{% url 'plan:main' %}">Перейти на главную</a><br>
                Пользователь: {{ user.username }}. 
                <a href="{% url 'plan:logout' %}">Выйти</a>
            </strong>
        {% else %}
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Войти"><br>
            </form>
            {% if error_message %}
                <p><strong>{{ error_message }}</strong></p>
            {% endif %}
        {% endif %}
    {% else %}
        <div id="head_menu">
            <img src="{% static 'images/red-cross.png' %}" alt="Госпитализация">
        </div>
        <div id="start_page">
            {% if debug %}
                <h1>{{ debug }}</h1><br>
            {% endif %}
            <h1>ПЛАН ГОСПИТАЛИЗАЦИИ</h1><br>
            {% if user.is_authenticated %}
                <strong>
                    <a href="{% url 'plan:main' %}">Перейти на главную</a><br>
                    Пользователь: {{ user.username }}. 
                    <a href="{% url 'plan:logout' %}">Выйти</a>
                </strong>
            {% else %}
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" value="Войти"><br>
                </form>
                {% if error_message %}
                    <p><strong>{{ error_message }}</strong></p>
                {% endif %}
            {% endif %}
        </div>
    {% endif %}
</body>
</html>

plan/templates/plan/logout.html
Выходим...
<form method="post" id="logout">
    {% csrf_token %}
    <input type="hidden" />
</form>
<script type="text/javascript">
    document.getElementById('logout').submit();
</script>

plan/templates/plan/main.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Госпитализация</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="icon" type="image/png" href="{% static 'favicon.png' %}">
    <meta name="description" content="Планирование госпитализации">
    <!--[if IE]><script src="{% static 'html5shiv/html5shiv.js' %}"></script><![endif]-->
    <!--[if IE]><script src="{% static 'html5shiv/html5shiv-printshiv.js' %}"></script><![endif]-->
</head>
<script src="{% static 'patients.js' %}"></script> 
<body>
    {% include './head.html' %} 
    {% if old_browser %}
        <div id="calendar">
            <table>
                <strong>Полный список пациентов находится под календарём</strong>
                {% for weeks in calendar %}
                <tr>
                    {% for day in weeks %}
                    <td class="{{ day.past }}">
                        <p>{{ day.date }}</p>
                        <p>{{ day.weekday }}</p>
                        <p><strong>Госпитализации:</strong></p>
                        {% for h in day.hosp %}
                            {% if h.confirmation %}
                                <a id="id_green" href="{% url 'plan:update' h.id %}">{{ h }}</a><br>
                            {% else %}
                                <a id="id_red" href="{% url 'plan:update' h.id %}">{{ h }}</a><br>
                            {% endif %}
                        {% empty %}
                            <p>Отсутствуют</p>
                        {% endfor %}
                        <p><strong>Операции:</strong></p>
                        {% for o in day.oper %}
                            {% if o.equipment == 'Стандарт' %}
                                <a id="id_based" href="{% url 'plan:update' o.id %}">{{ o }}</a><br>
                            {% elif o.equipment == 'Нейромонитор' %}
                                <a id="id_neuro" href="{% url 'plan:update' o.id %}">{{ o }}</a><br>
                            {% elif o.equipment == 'AWAKE' %}
                                <a id="id_awake" href="{% url 'plan:update' o.id %}">{{ o }}</a><br>
                            {% endif %}
                        {% empty %}
                            <p>Отсутствуют</p>
                        {% endfor %}
                    </td>
                    {% endfor %}
                </tr>
                {% endfor %}
            </table>
        </div>
        <table>
            {% if object_list|length > 0 %}
                <tr>
                    <th>Пациент</th>
                    <th>Госпитализация</th>
                </tr>
            {% else %}
                <p>Записи отсутствуют</p>
            {% endif %}
            {% for p in object_list %}
            <tr>
                <td><a href="{% url 'plan:update' p.id %}">{{ p.name }}</a></td>
                {% if p.hosp_date == none %}
                    <td><a href="{% url 'plan:update' p.id %}">Дата не указана</a></td>
                {% else %}
                    <td><a href="{% url 'plan:update' p.id %}">{{ p.hosp_date|date:"d-m-Y" }}</a></td>
                {% endif %}
            </tr>
            {% endfor %}
        </table>
    {% else %}
        <div id="calendar">
            <table>
                {% for weeks in calendar %}
                <tr>
                    {% for day in weeks %}
                    <td class="{{ day.past }}">
                        <p>{{ day.date }}</p>
                        <p>{{ day.weekday }}</p>
                        <p><strong>Госпитализации:</strong></p>
                        {% for h in day.hosp %}
                            {% if h.confirmation %}
                                <a id="id_green" href="{% url 'plan:update' h.id %}">{{ h }}</a><br>
                            {% else %}
                                <a id="id_red" href="{% url 'plan:update' h.id %}">{{ h }}</a><br>
                            {% endif %}
                        {% empty %}
                            <p>Отсутствуют</p>
                        {% endfor %}
                        <p><strong>Операции:</strong></p>
                        {% for o in day.oper %}
                            {% if o.equipment == 'Стандарт' %}
                                <a id="id_based" href="{% url 'plan:update' o.id %}">{{ o }}</a><br>
                            {% elif o.equipment == 'Нейромонитор' %}
                                <a id="id_neuro" href="{% url 'plan:update' o.id %}">{{ o }}</a><br>
                            {% elif o.equipment == 'AWAKE' %}
                                <a id="id_awake" href="{% url 'plan:update' o.id %}">{{ o }}</a><br>
                            {% endif %}
                        {% empty %}
                            <p>Отсутствуют</p>
                        {% endfor %}
                    </td>
                    {% endfor %}
                </tr>
                {% endfor %}
            </table>
        </div>
        <div class="dropdown_patients_list">
            <button onclick="click_function()" class="p_list">
                <img src="{% static 'images/menu.png' %}" width="35" height="35">
            </button>
            <div id="drop_list" class="dropdown_content">
                <table>
                    {% if object_list|length > 0 %}
                        <tr>
                            <th>Пациент</th>
                            <th>Госпитализация</th>
                        </tr>
                    {% else %}
                        <p>Записи отсутствуют</p>
                    {% endif %}
                    {% for p in object_list %}
                    <tr>
                        <td><a href="{% url 'plan:update' p.id %}">{{ p.name }}</a></td>
                        {% if p.hosp_date == none %}
                            <td><a href="{% url 'plan:update' p.id %}">Дата не указана</a></td>
                        {% else %}
                            <td><a href="{% url 'plan:update' p.id %}">{{ p.hosp_date|date:"d-m-Y" }}</a></td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    {% endif %}
</body>
</html>

plan/templates/plan/new.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Новый пациент</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="icon" type="image/png" href="{% static 'favicon.png' %}">
    <meta name="description" content="Создание новой записи">
    <!--[if IE]><script src="{% static 'html5shiv/html5shiv.js' %}"></script><![endif]-->
    <!--[if IE]><script src="{% static 'html5shiv/html5shiv-printshiv.js' %}"></script><![endif]-->
</head>
<body>
    {% include './head.html' %} 
    <br>
    <div class="split left">
        Шаблоны консультивного заключения: 
        <a href="{% static 'files/Шаблон.rtf' %}">.rtf</a>
        <a href="{% static 'files/Шаблон.docx' %}">.docx</a>
        {% if object %}
            <form method="post">
                {% csrf_token %}
                Консультативное заключение: 
                <a href="{{ object.doc.url }}" download>{{ object }}</a>
                {% if old_browser != True %}
                    <button type="submit" name="del_file" value="{{ object.id }}"
                    onClick="this.style='pointer-events: none;'; this.form.submit();">
                        Удалить файл
                    </button>
                {% endif %}
            </form>
        {% else %}
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <strong>{{ upload_form.file.errors }}</strong>
                {{ upload_form.file.label_tag }} {{ upload_form.file }}
                <input type="submit" name="file_obj" value="Загрузить"
                onClick="this.style='pointer-events: none;'; this.form.submit(); this.value='Отправка…';">
            </form>
        {% endif %}
        <form id="patient_form" method="post">
            {% csrf_token %}
            <ul>
            {% for field in form %}
                {% if field.widget_type == "hidden" %}
                    {{ field.errors }}
                    {{ field }}
                {% elif field.widget_type == "textarea" %}
                    <li>
                        <strong>{{ field.errors }}</strong>
                        {{ field.label_tag }} <br> {{ field }}
                    </li>
                {% else %}
                    <li>
                        <strong>{{ field.errors }}</strong>
                        {{ field.label_tag }} {{ field }}
                        {% if old_browser and field.widget_type == 'date' %}
                            <br> <strong>Пример ввода даты: 2020-06-29</strong>
                        {% endif %}
                    </li>
                {% endif %}
            {% endfor %}
            </ul>
            <input type="submit" name="pat_obj" value="Сохранить"
            onClick="this.style='pointer-events: none;'; this.form.submit(); this.value='Отправка…';">
        </form>
    </div>
    <div class="split right">
        {% if form.plain_text.value %}
            {{ form.plain_text.value|linebreaks }}
        {% endif %}
    </div>
</body>
</html>

plan/templates/plan/test.html
<strong>session</strong> {{ get_expiry_age }}<br>

<form action="{% url 'plan:test' %}" method="get">
    <select name="data">
        <option value="current" >current</option>
        <option value="next" selected>next</option>
    </select>
    <input type="submit" value="submit">
</form> 

{% for i in get_items %}
    {{ i }} 
{% endfor %}
<br>

<strong>multiple files</strong>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ multiple_file_form }}
    <input type="submit" name="multifile_obj" value="Upload">
</form>